name = "migratable"
main = "src/index.ts"
compatibility_date = "2024-09-25"

[[rules]]
type = "Text"
globs = ["**/*.sql"]
fallthrough = true

[[durable_objects.bindings]]
name = "DO"
class_name = "ExampleDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ExampleDO"]
